sonar.organization=matex2395
sonar.projectKey=Matex2395_TaskTimePredicter
sonar.projectName=TaskTimePredicter
sonar.sourceEncoding=UTF-8
sonar.language=cs
sonar.sources=.
sonar.tests=.
sonar.exclusions=*/bin/,/obj/*
sonar.dotnet.excludeTestProjects=true
